parameters:
#    nick_cage_me.example.class: BellGouk\NickCageMe\WebViewBundle\Example

services:
#    nick_cage_me.example:
#        class: %nick_cage_me.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
